### PR TITLE
Vega embed modification to support inline notebook view

### PR DESCRIPTION
**Pull request by AliciaSchep**
Per discussion in #11, I added to htmlwidgets.Rmd in data-raw some code to automatically do the bit of code modification to vega-embed.js to get around the rstudio bug.  

I also added the un-minified version of vega.js as I found that on my computer (ubuntu) using both the latest stable and daily build of rstudio I can't get the plots to show up in the viewer with the minified version.  Looking into it, it seems like the min version is one extremely long line and that my rstudio only ends up reading in part of it.   

One note: I am observing some weird behavior where this works great with "output: html_notebook" but with "html_document" and inline chunk output, it works for most of the Rmd files but not "first-example.Rmd".  When I look into why, it seems like the chunk is reading in the wrong version of the vegalite.js code (the package's htmlwidget code).  Curious whether if you try it out you will see that same problem.

### CODE REVIEW

**Comment by ijlyttle** [comment]
Will give it a spin today, thanks!

**Comment by ijlyttle** [comment]
I have tried on the three platforms at my disposal; I mostly succeeded:

### Ubuntu (RStudio IDE 1.1.139)

**Inline** did not work but I suspect this may be because I am piping RStudio server through ssh. No htmlwidget widget works inline. Console has a lot of "Resource not found" errors associated with htmlwidget files. (Weird that this is the first time I can remember trying this, though). **No problem or different issue** :) - I will update my IDE and report back!

**Viewer pane**, **Rendered RMarkdown** - displays just fine, like before.

### Windows (RStudio IDE 1.1.414)

No problem inline, viewerpane, or rendering. Although, interestingly, I did see this when I "inspected" the inline rendering: 

image

I suspect (although I defer to your judgement) that this is wrapped up in the issue that RStudio are now taking care-of.

### Mac (RStudio IDE 1.2.516)

**Inline** works, but I need to `library("htmlwidgets")` for this to work. With this version of the IDE, I don't seem to have the "inspect" tool available. Oddly enough, I can get the leaflet example to work without `library("htmlwidgets")`, and if I render the altair example *after* rendering the leaflet example, it works without `library("htmlwidgets")`.

```r
library(leaflet)

m <- leaflet() %>%
  addTiles() %>%  # Add default OpenStreetMap map tiles
  addMarkers(lng=174.768, lat=-36.852, popup="The birthplace of R")

m
```

**Viewer pane**, **Rendered RMarkdown** - displays just fine, like before.

---

I will update my RStudio on both Ubuntu and Mac to see if that changes anything.

**Comment by ijlyttle** [comment]
At this point I see no reason not to merge. Any thoughts?

Once I have updated my IDE's, I'll post more results.

**Comment by ijlyttle** [comment]
Update:

### Mac (RStudio IDE 1.2.516)

Works without qualification using your PR!

This IDE build (I think) incorporates the fix, so I tried with the "unfixed" altair (266147c). This was weird - it would not display inline the first time I would try, but it would display the second, and subsequent times. This may be *in fact* what was going on in my earlier test, but I did not test carefully enough.

### Ubuntu

(in progress, will update ASAP)

**Comment by ijlyttle** [comment]
I'm convinced! Thanks again!

**Comment by AliciaSchep** [comment]
I think the mousewheel event error (Windows section above) may actually have been fixed in another rstudio PR earlier https://github.com/rstudio/rstudio/pull/1503 but maybe after the version being tested?  I'm not sure though. I think that is an issue with the little javascript code that is being inserted rather than how/where it is being inserted.

Thanks for doing all this testing!  My thought is that this work-around should be used by the package until the rstudio fix is out in a stable release.

**Comment by ijlyttle** [comment]
My pleasure to do the testing - the least I could do, given your sleuthing!

I agree with your timetable, thus I propose to leave the original issue open until such time as we revert to the original vega-embed code.

**Pull request merged**
