### PR TITLE
add tooltip plugin

### PR DESCRIPTION
**Pull request by AliciaSchep**
Addition of the tooltip plugin (the js & css dependencies and 1 line of js code to vegalite.js).  

Note -- using this plugin means that a tooltip is generated with all data fields automatically. I saw on github issues that some of the altair & vega-tooltip people are thinking/planning on how to allow more customization in the future though.

Perhaps it is preferable to give people the option of adding this kind of tooltip, i.e. `vegalite` function could have a tooltip argument.

### CODE REVIEW

**Comment by ijlyttle** [comment]
I like what you've done here, thanks!

Can I ask you a couple of favors? 

- Can you note, either here or in [this Rmd](https://github.com/ijlyttle/altair/blob/master/data-raw/htmlwidget.Rmd) where you got the additional files, like where we can `httr::GET()` them from? I'd like to help our future selves by having a reproducible way of reconstituting the htmlwidgets stuff - you will see that this is presently kinda half-baked.

- I like your idea for adding a `tooltip` argument to the `vegalite()` function. Do you have any idea how we we would implement that? I'll think about it over the weekend and look around, but just on the off chance that you have been down this path already :)

Thanks!

**Comment by ijlyttle** [comment]
Following up on the `tooltip` argument question, I started reading a little bit (forgive me if this is review for you). There appear to be a [couple of ways](https://github.com/vega/vega-tooltip) to make a tooltip - the more-featureful way seems to be the [vega-tooltip](https://github.com/vega/vega-tooltip) you introduced.

Jumping down this particular rabbit-hole, I see there are a [lot of options already](https://github.com/vega/vega-tooltip/blob/master/docs/customizing_your_tooltip.md) for specifying tooltips. I am starting to see a way to to get from here to there on the `tooltip` argument.

As you suggest, our `vegalite()` function should have a `tooltip` argument. I think that we should provide a helper function, perhaps `vega_tooltip()` to build the [tooltip spec](https://github.com/vega/vega-tooltip/blob/master/docs/customizing_your_tooltip.md#options).

A helper function might look something like:

```R
vega_tooltip <- function(showAllFields = FALSE, 
                         fields = NULL, 
                         delay = 100, 
                         colorTheme = c("light", "dark"), 
                         sort = c("title", "value")) {

  # `fields` is a data-frame
  # I don't know how to specify callback functions (i.e. `onAppear`), so can deal-with later.
  ...

  jsonlite::toJSON(...)
}
```

I am happy to take a whack at such a helper function and make a PR into your PR. Eager to hear your thoughts!

**Comment by AliciaSchep** [comment]
I added the urls to the data-raw section -- I had not seen that section, definitely seems like a good idea to document & partially automate all that!  

I had not realized the extent to which you could customize the vega-tooltip -- thanks for sharing the links and write-up!  Really like what you started in the the PR to the PR.  I added a few comments there.  In terms of the git pr/branch mechanics not totally sure what the right way to proceed here so let me know if there is some git action I should take (e.g. merging your pr to my pr) that would be helpful...

**Comment by ijlyttle** [comment]
I had not seen your comment until just now - thanks for your feedback. 

I am getting close on my PR to your PR. On the one hand, this is a bit round-about, but on the other hand I like that we both get eyeballs on it (so long as it does not impinge too much on your time). 

Let's get through this set of PR's - I will let you know when I think I am ready for you to merge my stuff (soon, if Travis will agree 😡). I would value your thoughts and suggestions as a part of (hopefully) you accepting my PR, then I will be happy to accept your PR.

At some point, it may make sense to sort out some type of framework going forward.

**Comment by AliciaSchep** [comment]
Now has merged in your PR! With one tiny additional modification -- a package version minimum for listviewer in suggests (encountered error with examine with older version with tooltip having a callback).

**Comment by ijlyttle** [comment]
Thanks for all your help in this PR saga!

Fixes #4

**Pull request merged**
